name: LaTeX Workflow

on:
  push:
    paths:
      - 'doc/*.tex'

jobs:

  docs-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Comprobar gramática y ortografía
        uses: ChiefGokhlayeh/textidote-action@v5
        id: textidote
        with:
          working_directory: doc
          root_file: memoria.tex
          report_file: report.html
      
      - name: Subir informe de TeXtidote
        uses: actions/upload-artifact@v4
        with:
            name: textidote_report
            path: doc/report.html
      
      - name: Lanzar error si existen advertencias de TeXtidote 
        if: ${{ steps.textidote.outputs.num_warnings != 0 }}
        run: 'echo "::error file=memoria.tex::num_warnings: ${{ steps.textidote.outputs.num_warnings }}"; exit 1;'

      - name: Compilar memoria
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: doc
          root_file: memoria.tex
          
      - name: Subir PDF memoria
        uses: actions/upload-artifact@v4
        with:
          name: memoria-tfg
          path: doc/memoria.pdf
